package javaprogram;

public class MultipleException {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int res[]=new int[5];
		try {
			
			res[7]=10/0 ;
			System.out.print("result is : "+res);
		}
		catch (ArrayIndexOutOfBoundsException  e)
		{
			System.out.print("Exception is : "+e);
		}
		catch (ArithmeticException  e)
		{
			System.out.print("Exception is : "+e);
		}
		
	}

}
